### ISSUE TITLE
Does not work at all?! _SS_wrapper does not update

### ISSUE THREAD

**Issue by nicmare** [Musab-Hassan/slickscrolljs#5]
I am struggling for hours now and even copied your code. I can see in my source code that _SS_wrapper and _SS_dummy is present in DOM but if i scroll, they inline css value do no update. What do i miss?!
"z-index: 1; height: 100%; width: 100%; overflow: visible; top: 0px; left: 0px; position: sticky; transform: translate3d(0px, 0px, 0px);"

**Comment by Musab-Hassan** [comment]
Sorry for the late reply, been away from work. The example works on the body, not the window. Ensure your not scrolling in the window with your body as the overflowed content. Window scrolls cannot be modified, that's usually how most websites scroll, the content overflows the window. To scroll on body or any other element, ensure that element itself is the scroll frame and content overflows it. For example to add momentum scrolling to the body, you would have to make it a scroll frame.

Example: a body scroll frame (will scroll when content inside is longer than 100vh/100vw)
```css
body {
  overflow: auto;
  height: 100vh;
  width: 100vw;
}
```

Example: a test div scroll frame with content that overflows it (will scroll when content inside is longer than 100px/100px)
```css
.test {
  display: block;
  overflow: auto;
  height: 100px;
  width: 100px;
}
```
